### ISSUE TITLE
Can you publish the code for the combination of resnet and OREPA?

### ISSUE THREAD

**Issue by yyaoshuai** [JUGGHM/OREPA_CVPR2022#2]

**Comment by JUGGHM** [comment]
Thanks for your interest yyaoshuai! But I am confused what you are asking for. We have published all our codes on ResNets and (some) RepVGGs (and ResNeXt-50) composed of OREPA blocks. `blocks.py` and `blocks_repvgg.py` are for blocks used in ResNets and RepVGGs while the models are defined in the directory `models`.
