### ISSUE TITLE
about linear deep stem

### ISSUE THREAD

**Issue by clearlon** [JUGGHM/OREPA_CVPR2022#5]
Hi,
Thank you for your great work. 
Where is the implementation code for the "Linear Deep Dry" method?
Is it in "OREPA_LargeConvBase"?

**Comment by JUGGHM** [comment]
> Hi, Thank you for your great work. Where is the implementation code for the "Linear Deep Dry" method? Is it in "OREPA_LargeConvBase"?

That's right. Actually we use `OREPA_LargeConv` where the 3x3 layers in a deep stem are re-parameterized as well. And thanks for your interest!

**Comment by clearlon** [comment]
Thank you!
